name: Python application test with Github Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Debug: show Python & pip versions
      - name: Show environment info
        run: |
          which python
          python --version
          pip --version
          pip list

      - name: Install dependencies
        run: |
          set -x   # enable debug output
          make install

      - name: Lint with pylint
        run: |
          set -x
          make lint

      - name: Test with pytest
        run: |
          set -x
          make test || { echo "❌ Pytest failed"; exit 1; }

      - name: Format code
        run: |
          set -x
          make format
