name: Python application test with Github Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint with pylint
        run: pylint your_module/

      - name: Test with pytest
        run: pytest

      - name: Format code with black
        run: black .
